---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/

---
spring:
  profiles: subject
  application:
    name: lab-4-subject
words: I,You,He,She,It

---
spring:
  profiles: subject2
  application:
    name: lab-4-subject
words: Peter,Paul,Mary
  
---
spring:
  profiles: verb
  application:
    name: lab-4-verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
  application:
    name: lab-4-article
words: a,the

---
spring:
  profiles: adjective
  application:
    name: lab-4-adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
  application:
    name: lab-4-noun
words: boat,book,vote,seat,backpack,partition,groundhog
  
